---
#
# Required Information --------------------------------------------------------
# change lines 5 - 15
title: "Windenergy and repowering potential in Rhineland-Palatinate from 2021 until 2030"
type: "Master's Thesis"
author: "Elias Cuadra Braatz"
matriculation_number: "219202265"
date: "MMMM dd, yyyy"
university: "Universität Koblenz - Landau"
institute: "Institute of Environmental Sciences" 
chair: "Environmental Economics"
chair2: "Chair: Prof. Oliver Frör"
advisor1: "Dr. Stefan Jergentz"
advisor2: "Dr. Nanki Sidhu"            
program: "Master of Environmental Sciences"
#
abstract: |  
  `r if(knitr:::is_latex_output()) paste(readLines("prelim/00-abstract.Rmd"), collapse = '\n  ')`
acknowledge: |  
  `r if(knitr:::is_latex_output()) paste(readLines("prelim/00-acknowledge.Rmd"), collapse = '\n  ')`
abbreviations: |  
  `r if(knitr:::is_latex_output()) paste(readLines("prelim/00-abbreviations.Rmd"), collapse = '\n  ')`
lot: true                              # list of tables
lof: true                              # list of figures
link-citations: true
bibliography: bib/references.bib       # bibliography file
#
# Rendering Options -----------------------------------------------------------
#
knit: "bookdown::render_book"
output: 
  huwiwidown::thesis_pdf 
space_between_paragraphs: true       # if you want spaces bt paragraph
# header-includes:     # if including additional latex packages or commands
  # - \setlength{\parindent}{17pt}
---


```{r include_packages, include = FALSE}
# This chunk ensures that the `huwiwidown` package is installed and loaded. This
# package includes the template files for the thesis.
if (!require(devtools)) {
  install.packages("devtools", repos = "http://cran.rstudio.com")
}
if (!require(huwiwidown)) {
  devtools::install_github("phister/huwiwidown")
  library(huwiwidown)
}
```

<!-- 
The {.unnumbered} option here means that the introduction will be "Section  0."
You can also use {-} for no numbers on section. 
-->

<!--
The body of the thesis starts underneath the text below. Feel free to delete
everything below this.
-->

# About this Thesis Template {-}

Welcome to the thesis template. This template is based on (and in many places 
copied directly from) the HU Berlin School of Business and Economics LaTeX 
template, but hopefully it will provide a nicer interface for those that have
never used LaTeX before. 

## Why use R Markdown? {-}

_R Markdown_ creates a simple and straightforward way to interface with the
beauty of LaTeX. Packages have been written in **R** to work directly with LaTeX
to produce nicely formatting tables and paragraphs. 

_R Markdown_ also allows you to read in your data, to analyze it and to
visualize it using **R** functions, and also to provide the documentation and
commentary on the results of your project. Using _R Markdown_ will also allow
you to easily keep track of your analyses in **R** chunks of code, with the 
resulting plots and output included as well.