# Introduction

This thesis was done and written in scientific recognition of the effects of climate change as reported by the Intergovernmental Panel on Climate Change (IPCC) and the  the importance of reducing greenhouse gas emissions to prevent a rising of the global average annual temperature below 2 $^\circ$C  @IntergovernmentalPanelonClimateChange.2014. To achieve this goal many countries around the globe put special effort in greenhouse gas reduction and the transformation of their industry. For the fulfillment of this purpose the Federal Climate Protection Act was passed in 2019 with latest changes in 2021 and states that the greenhouse gas reduction in comparison to the year 1990 should be at least 65% (former 55%) in 2030 and at least 88% in 2040 and from 2045 onward there should be a net greenhouse gas neutrality @BundesamtfurJustiz.2019. The tightening of these reduction targets came through the recent decision and the subsequent press release No. 31 from April 29, 2021 @Bundesverfassungsgericht.24.03.2021 of the first Senate of the Federal Constitutional Court which states that the regulations of 2019 on the national climate protection targets and the annual emission quantities permitted up to 2030 are incompatible with fundamental rights, as there are not sufficient criteria for further emission reductions from 2031 onward. It is stated that the legal requirements are not sufficient to bring about a timely transition to climate neutrality. The German legislature has therefore published the adjusted edition of this act that strives for a faster development of renewable energies and the energy transition in general @BundesministeriumfurUmweltNaturschutzundnukleareSicherheit.12.05.2021. The central control instrument for the expansion of renewable energies is an will remain the Renewable Energy Act (EEG) with its latest edition of 2021. The aim of the EEG is to rebuild the energy supply and to increase the share of renewable energies in the electricity supply to at least 65% by 2030 and that all the electricity consumed and generated in Germany will be greenhouse gas neutral by 2050 @BundesamtfurJustiz.2021. The tools of the EEG are fixed feed-in tariffs for young technologies such as wind and solar energy to enter the market and guaranteed purchase and priority feed-in of electricity. From 2017, the level of remuneration for renewable electricity will not be set by the state, as was previously the case, but will be determined through tenders on the market to create a free market economy.

Similarly to the Federal law there is the State Climate Protection Act (Landesklimaschutzgesetz - LKSG) of Rhineland-Palatinate (RLP) that came into force on August 23, 2014 states that the total of all greenhouse gas emissions in RLP have to be reduced by at least 40% by 2020 compared to the base year 1990. Further the aim is to reduce greenhouse gas emissions by 100% by 2050, but at least by 90% @RheinlandPfalz.19.08.2014. Likewise the coalition agreement from 2021 to 2026 of the current government of RLP desires the goal of “100% renewable energies by 2030” and it can be assumed that the Climate Protection Act will be amended @SPDGruneFDP.2021. This shows that this study is still very topical on a state level and also highly embedded in a dynamic socio-economic context.

Whether on a global, national or a local scale it is clear that a cornerstone of the transition of our society to a ecological sustainable form is the change of our fossil fuel based economy to a economy that is powered by renewable energies. Thus, the energy transition is regarded as the main focus of the strategy to climate neutrality and RLP wants to play a pioneering role in the implementation of the energy transition . In addition to energy from the sun, water and biomass, two thirds of the electricity generated in 2030 should come from wind power and is therefore the subject of the research presented in this master thesis @LandesregierungRheinlandPfalz.2021. This study was carried out on behalf of the state-owned Energy Agency of Rhineland-Palatinate @EnergieagenturRheinlandPfalz.2021 within the project "Municipal Greenhouse Gas Accounting and Regional Climate Protection Portals in Rhineland-Palatinate" @KomBiReK.2021, which is funded by the European Regional Development Fund @EuropeanRegionalDevelopmentFund.2021 and the state of RLP. This project supports the creation of municipal climate protection measures in order to mitigate CO\textsubscript{2} emissions and achieve the climate protection goals of the municipalities and the state and thereby increases regional added value, ensures sustainability and thus improves the quality of life of all citizens. 

As of 2017, the gross electricity generation in RLP from wind power was 5.9 TWh, which was 29% of the total 20.7 TWh of electricity generated in the state @Lehnert.2020. By 2019, the electricity generated from wind turbines (WTs) has already increased to more than 6.7 TWh @AmprionGmbH.2019. It can be assumed that, on the one hand, electricity consumption will increase in the future due to the electrification of transport and domestic heating, and on the other hand, efficiency measures can also lead to a lower energy consumption. Whereas, some past studies and scenarios estimated a slight increase and others a slight decrease but on average a relatively unchanged electricity consumption in Germany, which is currently about 560 TWh @NormanGerhardt.2015, the newest press release of the Federal Ministry for Economic Affairs and Energy makes it very clear. An increase to a previous prediction of about 12% from 580 to 655 TWh is expected @AndreasMertens.13.07.2021, and further studies will follow in the autumn of 2021. If RLP wants to become independent of electricity imports and achieve the self-set goals of covering two thirds of the electricity consumption from wind power with an estimated electricity demand of 33 TWh in 2030, electricity supply from WTs must be about 22 TWh per year. There are two ways of increasing the amount of electricity generated by wind energy. Either areas can be used that have already been identified as suitable for WTs but have not yet been built on, or else, existing old systems whose absolute electricity feed-in quantity is low, can be replaced by new, taller and more efficient systems through so-called "repowering".

\newpage

The aim of this work is to develop a method for calculating the wind energy potential and its related area consumption at a state level regarding the two described options. The objective is then to evaluate the desired expansion and emission reduction targets up to 2030 and assess weather they are realistic and in line with the current distance rules and approval procedures and give recommendations for policy makers. Accordingly, the central questions of this work are:

1.	How much electricity per area can be generated by a new WT from 2021 until 2030 in RLP?

2.	What is the potential when all wind turbines built before 2005 are repowered?

3.	How much area is needed to generate the target amount of 22 TWh?

In order to answer these questions the data analysis and results of the master and movement data provided by the transmission system operator Amprion and of the market master data register (MaStR) is Presented in chapter 3 and 4. The gained results are discussed subsequently in chapter 5 and the paper ends with a summary of the main findings and a recommendation to policy makers in the concluding chapter number 6. To introduce the reader with all the necessary background information on the topic, the scientific and technical fundamentals, that are a prerequisite to this thesis and the assessment of the electricity yield from onshore WTs in RLP, are explained in the following chapter number 2.   

\newpage


