# State of the art

## Technical and physical basics

<div style="text-align: justify">
Wind energy has been used by humans for thousands of years, but the generation of electrical power has only been possible since the 19th century with the beginning of industrialization and is now the subject of constant research and development in the context of the energy transition @Wikipedia.2021. A wind turbine usually consists of the three main components rotor blades, nacelle and tower. The nacelle contains besides other elements the gearbox, the generator, the transformer and the control system @MladenBosnjakovic.2013. The mostly three rotor blades are attached to the rotor hub and absorb the kinetic energy of the wind and convert it into a rotary motion. If the winds are too strong, the rotor blades can be “taken out of the wind” by adjusting the blades, thus protecting the system from damage. Mainly the gearbox and the generator convert the kinetic energy into electricity. However, there are also systems with direct drive and without gear. The nacelle can be rotated to an optimal position when the wind conditions change, and an electromagnetic brake helps to shut down the system when the winds are too strong or during maintenance work. In addition to its load-bearing function, the tower also contains the power lines that conduct electricity to the grid connection of the distribution network @NetzKonstrukteur.16.11.2020.

The transmission system operators, in this case Amprion, are obliged to publish master and so-called movement data for each calendar year in accordance with section 77 Renewable Energy Act 2017. These movement data include the annual electricity generation and the underlying tariff for each renewable energy system. The movement data for Rhineland-Palatinate are currently available until 2019. The total amount of electricity fed in with remuneration in 2019 from wind turbines in RLP is 6,782,180,753 kWh, i.e. approx. 6,782 TWh @EnergieagenturRheinlandPfalz.2019.

The amount of electricity generated by a wind turbine, the electricity yield, can be derived from the physical relationship between the kinetic energy and the power of the wind. Without claiming to be exhaustive, the following applies:


\begin{equation}
E_{kin} = \frac{1}{2}mv^2
\end{equation}

The air throughput or mass flow $\hat{m}$ that flows through the area swept by the rotor blades in a certain time can be calculated by multiplying the air density, rotor area and wind speed as well as the time interval required with:

\begin{equation}
\hat{m}=\rho A V
\end{equation}

The power P is equal to the energy per unit of time $\hat{E}$. This results in the power of the wind with:

\begin{equation}
P_{wind}=\hat{E}=\frac{1}{2}\hat{m}v^2=\frac{1}{2} \rho \pi r^2 v^3
\end{equation}



</div>