# Data

## Materials

The Master and Movement data from the transmission system operator Amprion of the years 2017 to 2019 prepared by the energy agency of RLP is used to analyze the electricity yield mainly over the rated capacity and the commissioning date. Amprion lists 1,702 WT's in RLP in 2019. In comparison the Structure and Approval Directorate North registers 1,704 WT's with technical details and coordinate references that are connected to the public grid. In addition the Marked Master Data Register (MaStR) of the Federal Network Agency @Marktstammdatenregister.2020, in which all electricity and gas generation systems must be registered, is used. The MaStR contains technical details of the WT's and also the exact coordinate refernces of their location but not the electricity yield. The data from Amprion and the MaStR both contain a system key according to the Renewable Energy Law, by which they can be joined to a single data set which contains the electricity yield as well as the coordinates for the assessment of the area consumption per quantity of generated electricity.

For the preparation and the analysis of the data R version 4.0.5 (2021-03-31) -- "Shake and Throw" and RStudio Version 1.4.1106 were used. Due to exhaustive code and iterative preparation steps the full documentation can not be displayed here but is to be found on [https://github.com/EliasCuadra/master-thesis-repowering](https://github.com/EliasCuadra/master-thesis-repowering) with explanatory README.md files that contain description of variables and proccessing steps. Nonetheless, important aspects or code chunks are directly included or can be found in the appendix.

## Methods

### Preparation and Analysis of data from the transmission system operator Amprion

### Area consumption of WT'S in RLP

### CO\textsubscript{2} reduction potential

### Repowering potential  





```{r table1, echo=FALSE}
col_names <- c(
  "3m", "6m", "1yr", "2yr", "3yr", "5yr", "7yr", "10yr", "12yr", "15yr"
)
means     <- c(
  3.138, 3.191, 3.307, 3.544, 3.756, 4.093, 4.354, 4.621, 4.741, 4.878
)
stddev    <- c(
  0.915, 0.919, 0.935, 0.910, 0.876, 0.825, 0.803, 0.776, 0.768, 0.762
)
row_names <- c("Mean", "StD")

df <- matrix(data = c(means, stddev), nrow = 2, byrow = T)
rownames(df) <- row_names
colnames(df) <- col_names
df <- data.frame(df)
knitr::kable(
  df,
  booktabs = TRUE,
  caption = "Detailed descriptive statistics of location and dispersion for 2100 observed swap rates for the period from February 15, 1999 to March 2, 2007. Swap rates measured as 3.12 (instead of 0.0312).",
  col.names = col_names, 
  escape = FALSE
) %>%
kable_styling(latex_options = c("HOLD_position")) %>%
row_spec(2, hline_after = T)
```

* Allows the reader to judge whether the sample is biased or to evaluate 
  possible impacts of outliers, for example.

* Here tables can be easily integrated using the `kable()` function in the
  `knitr` package (with perhaps some additional help from the `kableExtra`
  package). `kable()` will automatically generate a label for the table
  environment. That way you don't have to manually enter in the table in LaTex,
  you can embed tables from R code. 

* Tables can be referenced using `\@ref(label)`, where `label` is `tab:<name>`,
  where `<name>` is the code chunk label.

* The appearance may look different to tables directly typed with LaTex, due to
  limitations in `kable()`. To compare:
    \begin{table}[ht]

    \begin{center}
        {\footnotesize
        \begin{tabular}{l|cccccccccc}
            \hline \hline
                      & 3m    & 6m    & 1yr   & 2yr   & 3yr   & 5yr   & 7yr   & 10yr  & 12yr  & 15yr   \\
            \hline
                Mean   & 3.138 & 3.191 & 3.307 & 3.544 & 3.756 & 4.093 & 4.354 & 4.621 & 4.741 & 4.878  \\
                StD    & 0.915 & 0.919 & 0.935 & 0.910 & 0.876 & 0.825 & 0.803 & 0.776 & 0.768 & 0.762  \\
            \hline \hline
        \end{tabular}}
    \end{center}
    \caption{This table was handwritten with LaTeX.}
    \label{tab:table2}
    \end{table}
