# Discussion

This thesis has already presented the state of the art, methodology, calculations and analysis, and in this chapter the results will be critically discussed and placed in a wider context. At the beginning of this thesis it was shown that the topic of the energy transition and in particular the development of wind power onshore is given high social relevance as well as importance in terms of security of supply @ARD.2021. Against the background of the German federal election in September 2021 and the ongoing trend-setting coalition negotiations, the energy transition will be visibly highlighted. This state of focus on the current development and imminent transformation of the energy systems is of course not a German phenomenon, but rather preoccupies the European Union as well as all communities in the whole world. Due to the consequences of climate change and changes in the environment and supply systems, certain regions are being affected more than others. In this sense the research and development of renewable energy systems is more topical than ever. Renowned institutions such as the Fraunhofer Society, the Institute for Climate Impact Research and many universities, organizations and businesses deal in detail with the question of how exactly this transformation can succeed. One answer to this question seems to be clear: the capacity of onshore wind power will be further expanded! This is reflected in the development trends of Deutsche WindGuard shown in Chapter 2 and the other reports presented on the technical development of wind power. However, there are certain limits to wind power on land. The availability of suitable locations is limited by the amount of wind, nature conservation issues and of course by the acceptance of the citizens @Stede.2019. For this reason, a potential analysis, as in this case for Rhineland-Palatinate, which must then be compared with the climate protection goals to be achieved, is logical. In this master's thesis, based on the feed-in data from the transmission system operator Amprion and the data from the MaStR, a relatively technical but robust analysis of the expected feed-in quantities and the expansion rate as well as the area requirements was made. Due to the high reliability of the publicly available data and the correspondence with the most recent and largest German DWG study, this result is very reliable. However, the criticism here is that the expansion of wind power or an individual system or an entire wind farm cannot be viewed in an idealized manner, but always depends on legal and social regulators and thus eludes a specific scientific analysis. Nevertheless, these results are very informative and the basic statements can be made:

1. The total number of wind turbines will continue to increase in RLP and the expected number of 2,500 will be reached in 2030 if the expansion rate remains the same.

2. The expected amount of electricity that can be fed in by a wind power plant built around the year 2026, will rise steadily, and would be around 15,000 MWh at an average wind speed of 6 m/s, depending on the manufacturer's information.

3. According to the modeling done for this study, there is an average feed-in quantity over all WTs of a minimum of 7,400 MWh in 2021 and about 10,000 MWh in 2030, assuming a linear increase. With an exponential increase, the quantities could even reach 10,000 MWh in 2021 and over 15,000 MWh in 2030. It is therefore difficult to reliably determine a specific value here, since the speed of expansion is strongly related to political decisions.

4. The total number of repowering plants, i.e. plants with a commissioning date before 2006, is 514 with a total feed-in quantity of 841 GWh. If all of these systems were to be replaced with an output of 12,500 MWh, there would be a potential increase of 5584 GWh additionally.

5. The rotor diameter as well as the hub height will increase to more than 160 m which means the total height of WTs will increase up to 250 m and more. 

6. The predicted electricity density for 2030 for RLP is 40.5 kWh/m\textsuperscript{2} and relates to a constant power output of 4.6 W/m\textsuperscript{2}. With this predicted power density, the amount of area required to cover the demand of 22 TWh in 2030 would be roughly 2.7% of the total area of RLP. As the state of the art of the manufacturers show the output for newly commissioned WTs will definitely increase to above 60 kWh/m\textsuperscript{2} within the next five years. Due to fast expansion the electricity density could therefore increase up to an average of 63.5 kWh/m\textsuperscript{2} in 2030 which relates to a constant power output of 7.2 W/m\textsuperscript{2}. With this higher predicted power density, the amount of area required to cover the demand of 22 TWh in 2030 would be roughly 1.75% of the total area of RLP.

7. This means at a final and main result the targets presented by the government can be reached with a specific, fast and unbureaucratic expansion of WTs until they cover around 2% of the state.

These results were also confirmed based on personal training and work at a project development company. For their conservative profitability calculations, for example in Baden-Württemberg, project development companies expect yields of 13,000 - 15,000 MWh at wind speeds of around 6 m/s or even a bit below that for a Nordex N163-5.X wind turbine with commissioning in 2026. A study by Jäger et. al from 2016 estimated the technical potential in Baden-Württemberg which is the neighboring state between 11.8 and 29.1 TWh but argues that this might not be feasible @Jager.2016.

If an an average electricity generation of 7,400 MWh/a per WT is assumed, the number of WTs needed to generate the demanded 22 TWh is around 2,973 WTs. If on average 8,050 MWh/a could be harvested then this would require around 2,733 WTs. It seems that if the average growth of the total number of WTs in RLP continues as predicted initially, the goal of around 2,500 WTs in RLP is very realistic. If the 22 TWh shall be generated with 2,500 WTs the average annual output must be 8,800 MWh, which also seems quite realistic because the numbers presented before are conservative and only estimates for the year 2021 and will certainly increase over the next ten years. Of course, WTs with lower total electricity yield would have to be repowered additionally to increase the mean output and effort has to be made to push ahead with the expansion of WTs in RLP, but it shows that it is certainly not out of the scope. On the contrary to the technical potential, due to legal reasons and resistance from the citizens, the increase was slowed down sharply from 92 newly commissioned WTs in 2017 to 27 newly commissioned WTs in 2019 @EnergieagenturRheinlandPfalz.2019. Experts from the wind industry particularly criticize the difficult approval procedures. The biggest mistake of the federal government was to introduce an "obligation to tender" for new wind turbines that slows down the whole process @NickSchader.2021.

It can be seen that the power output per area can even exceed the value of 7 W/m\textsuperscript{2} described by Linow @SvenLinow.2020. It also demonstrates how the required wind speed is significantly lower to generate a higher electricity density when reducing the distance of WTs to each other. In the best case and not an unrealistic scenario it can therefore be seen that it might be reasonable to believe that the electricity demand of 22 TWh can be generated in the year 2030 with an average wind speed of 6 m/s by covering only 1.7% of the country with WTs. If compared with the occurrence of this wind speed shown in Figure \@ref(fig:wind) at 140 m above ground, it seems very reasonable to believe that with a hub height of more than 160 m the average wind speed will increase and therefore the electricity yield of covering the mentioned 2% of the country can even generate more electricity. 


\newpage

All this means that RLP meets the expansion targets in the area of wind power and the state's climate protection goals can also be achieved from a technical point of view. However, it should be noted that this analysis did not adequately address the regulatory and societal hurdles. In project development, for example, many areas cannot be used for wind power projects due to restrictions and community taboo criteria. The most important restrictions include sufficient distance from landscape and nature protection areas and endangered animal and plant species such as the red kite, black stork, sea eagle or certain bat and newt species as well as military areas, radars for aviation and radio relay routes, etc. These types of detailed analyses related to regulatory and societal restrictions are not the main focus of the work presented in this thesis, but are absolutely necessary in practice in order to implement wind power projects. However, this also eludes a specific quantitative analysis, as these restrictions are constantly changing and therefore cannot be clearly identified over a longer period of time.


\newpage






















