# Conclusion

The results of this work show that the expansion targets for electricity generation of 22 TWh from wind power in 2030 can indeed be achieved with 2,500 WTs and covering 2% of the state, which was already defined in 2012 as a realistic number for the available area @StefanBofingeretal.2012. For this, a politically or socially controlled designation of areas is necessary. This is a concrete recommendation for action to the state government. Since the bigger hurdles in this process lie in nature conservation and in the resistance of the population, measures should be taken especially here. With regard to nature conservation, the main concern here is the creation of compensatory habitats and the use of mechanisms and techniques, such as the shutdown of systems in situations where animal species are endangered @BUND&Nabu.2017. For this purpose, further research on the behaviour of the animals is recommended and it should be checked whether the endangerment of red list species can be minimized. Another very important topic is acceptance by the local people. In particular, it should be investigated how better participation and communication increases the acceptance, which is already at a high level, of such projects and reduces resistance @FachagenturWindenergieanLand.2020. The issues of noise pollution, the optically oppressive effect and the throwing of ice are also a constant cause of concern in wind power projects. A lot of energy is already invested in engineering research into noise reduction and rotor blade heating, and this is certainly recommended for the future and will be continuously developed.

It is therefore almost certain that the expansion of wind power in RLP will proceed at a similar speed or even accelerated, the expansion targets and thus also the targets for climate protection by 2030 will be achieved. However, this only applies explicitly to the assumed electricity demand of 33 TWh of which 22 TWh can come from wind power. However, it can be assumed that the electricity demand will continue to increase due to the electrification of mobility and heating and also for energy-intensive industries, above all BASF in Ludwigshafen with extremely energy-intensive processes such as steam cracking. Whether it is possible to run the entire economy of RLP based solely on its own wind and solar power remains questionable and must be investigated in further studies.


