\appendix
# Appendix


## Code chunk 1
```{r analysis, eval=FALSE, echo=TRUE}
##################################
#Statistical analysis of the data#
##################################

#packages#
Sys.setenv(LANG = "en")
pacman::p_load(rio, data.table, tidyverse, tidyr, purrr, magrittr, compare, 
               ggplot2, DiagrammeR)

#Import data and format columns
amprion_2015 <- read.csv("results_of_preparation/amprion_2015_processed.csv")
amprion_2016 <- read.csv("results_of_preparation/amprion_2016_processed.csv")
amprion_2017 <- read.csv("results_of_preparation/amprion_2017_processed.csv")
amprion_2018 <- read.csv("results_of_preparation/amprion_2018_processed.csv")
amprion_2019 <- read.csv("results_of_preparation/amprion_2019_processed.csv")

#formatting commissioning date
amprion_2015$inbetriebnahme <- as.Date(amprion_2015$inbetriebnahme, "%Y-%m-%d")
amprion_2016$inbetriebnahme <- as.Date(amprion_2016$inbetriebnahme, "%Y-%m-%d")
amprion_2017$inbetriebnahme <- as.Date(amprion_2017$inbetriebnahme, "%Y-%m-%d")
amprion_2018$inbetriebnahme <- as.Date(amprion_2018$inbetriebnahme, "%Y-%m-%d")
amprion_2019$inbetriebnahme <- as.Date(amprion_2019$inbetriebnahme, "%Y-%m-%d")

#Linear model of electricity yield over commissioning date 2017 - 2019
#2017
lm_electricity_yield_2017 <- lm(
  amprion_2017$menge_mwh ~ amprion_2017$inbetriebnahme)
summary(lm_electricity_yield_2017)
plot(lm_electricity_yield_2017)

#2018
lm_electricity_yield_2018 <- lm(
  amprion_2018$menge_mwh ~ amprion_2018$inbetriebnahme)
summary(lm_electricity_yield_2018)
plot(lm_electricity_yield_2018)

#2019
lm_electricity_yield_2019 <- lm(
  amprion_2019$menge_mwh ~ amprion_2019$inbetriebnahme)
summary(lm_electricity_yield_2019)
par(mfrow = c(2, 2))
plot(lm_electricity_yield_2019)

#check polynomial model
#2017
pm_electricity_yield_2017 <- lm(
  amprion_2017$menge_mwh ~ 
    poly(amprion_2017$inbetriebnahme, 3))
summary(pm_electricity_yield_2017)
plot(pm_electricity_yield_2017)

#2018
pm_electricity_yield_2018 <- lm(
  amprion_2018$menge_mwh ~ 
    poly(amprion_2018$inbetriebnahme, 3))
summary(pm_electricity_yield_2018)
plot(pm_electricity_yield_2018)

#2019
pm_electricity_yield_2019 <- lm(
  amprion_2019$menge_mwh ~ 
    poly(amprion_2019$inbetriebnahme, 3))
summary(pm_electricity_yield_2019)
plot(pm_electricity_yield_2019)

#Plot the values with linear and polynomial trends for 2017 - 2019
pelectricity_yield_2019_poly <- ggplot() +
  geom_point(data = amprion_2017, aes(x=inbetriebnahme, y=menge_mwh), 
             size = 0.4, colour = "#03a1fc") +
  geom_point(data = amprion_2018, aes(x=inbetriebnahme, y=menge_mwh), 
             size = 0.4, colour = "#fc5a03") +
  geom_point(data = amprion_2019, aes(x=inbetriebnahme, y=menge_mwh), 
             size = 0.4, colour = "#94fc03") +
  geom_smooth(data = amprion_2017, 
              aes(x=inbetriebnahme, y=menge_mwh, colour = "2017"), 
              method=lm, se=TRUE, fullrange = TRUE, size = 0.5)  +
  geom_smooth(data = amprion_2018, 
              aes(x=inbetriebnahme, y=menge_mwh, colour = "2018"), 
              method=lm, se=TRUE, fullrange = TRUE, size = 0.5)  +
  geom_smooth(data = amprion_2019, 
              aes(x=inbetriebnahme, y=menge_mwh, colour = "2019"), 
              method=lm, se=TRUE, fullrange = TRUE, size = 0.5)  +
  geom_smooth(data = amprion_2017, 
              aes(x=inbetriebnahme, y=menge_mwh, colour = "2017"), 
              method= "lm", formula = y ~ poly(x, 3), 
              fullrange = TRUE, size = 0.5)  +
  geom_smooth(data = amprion_2018, 
              aes(x=inbetriebnahme, y=menge_mwh, colour = "2018"), 
              method= "lm", formula = y ~ poly(x, 3), 
              fullrange = TRUE, size = 0.5)  +
  geom_smooth(data = amprion_2019, 
              aes(x=inbetriebnahme, y=menge_mwh, colour = "2019"), 
              method= "lm", formula = y ~ poly(x, 3), 
              fullrange = TRUE, size = 0.5)  +
  theme_light() +
  scale_x_date(limits = as.Date(c("1990-01-01","2030-12-31"))) +
  ylim(-1000, 20000) +
  xlab("Commissioning Date") +
  ylab("Electricity yield per WT and year [MWh]") +
  theme( axis.text=element_text(size=11),
         axis.title=element_text(size=12),
         plot.title = element_text(size=14),
         legend.position = c(0.85, 0.9),
         legend.direction = "horizontal") +
  geom_hline(yintercept = 7400, linetype = 'dashed', size = 0.25) +
  annotate(geom="text",x=as.Date("1997-01-01"),
           y=6500,label="mean of ~ 7,400 MWh/a in 2021 with linear trends",
           size = 2.5) +
  geom_hline(yintercept = 10000, linetype = 'dashed', size = 0.25) +
  annotate(geom="text",x=as.Date("2000-01-01"),
           y=11000,label="mean of ~ 10,000 MWh/a in 2030 with linear trends", 
           size = 2.5) +
  geom_hline(yintercept = 15000, linetype = 'dashed', size = 0.25) +
  annotate(geom="text",x=as.Date("2003-01-01"),
           y=14200, label="> 15,000 MWh/a in 2030 with polynomial models", 
           size = 2.5) +
  annotate(geom="text",x=as.Date("2026-01-01"),
           y=2000,label= "All adj. R² (3rd poly) ~ 72 %", size = 2.5) +
  annotate(geom="text",x=as.Date("2026-01-01"),
           y=3500,label= "All R² (linear) ~ 68 - 70 %", size = 2.5) +
  annotate(geom="text",x=as.Date("2026-01-01"),
           y=400,label="p-values all << 0.001", size = 2.5) +
  scale_colour_manual(name = "Year", values=c("#03a1fc", "#fc5a03", "#94fc03")) 

#print plot
pelectricity_yield_2019_poly +  theme(legend.position = c(0.25,0.9))

#save plot as image
ggsave("results_of_analysis/electricity_yield_2017-2019.png",
       plot = last_plot(),
       dpi = 900,
       width = 7,
       height = 4)

#linear models with electricity over rated capacity 2019
lm_e_over_rated_capacity_2019 <- lm(
  amprion_2019$menge_mwh ~ amprion_2019$leistung)
summary(lm_e_over_rated_capacity_2019)
plot(lm_e_over_rated_capacity_2019)

#Plot electricity yield over rated capacity with linear trend 2017 - 2019
pe_over_ratedcapacity_2019 <- ggplot() +
  geom_point(data = amprion_2017, aes(x=leistung, y=menge_mwh), 
             size = 0.4, colour = "#03a1fc") +
  geom_point(data = amprion_2018, aes(x=leistung, y=menge_mwh), 
             size = 0.4, colour = "#fc5a03") +
  geom_point(data = amprion_2019, aes(x=leistung, y=menge_mwh), 
             size = 0.4, colour = "#94fc03") +
  geom_smooth(data = amprion_2017, 
              aes(x=leistung, y=menge_mwh, colour = "2017"), 
              method=lm, se=TRUE, fullrange = TRUE)  +
  geom_smooth(data = amprion_2018, 
              aes(x=leistung, y=menge_mwh, colour = "2018"), 
              method=lm, se=TRUE, fullrange = TRUE)  +
  geom_smooth(data = amprion_2019, 
              aes(x=leistung, y=menge_mwh, colour = "2019"), 
              method=lm, se=TRUE, fullrange = TRUE)  +
  theme_light() +
  ylim(-1000, 20000) +
  xlim(0,8000) +
  xlab("Rated capacity (kW)") +
  ylab("Electricity yield per year [MWh/a]") +
  theme( axis.text=element_text(size=12),
         axis.title=element_text(size=13),
         plot.title = element_text(size=16),
         legend.position = c(0.85, 0.9),
         legend.direction = "horizontal") +
  annotate(geom="text",x=6500,
           y=3500,label= "R² = ~ 79 %") +
  scale_colour_manual(name = "Year", values=c("#03a1fc", "#fc5a03", "#94fc03")) 

#print plot
pe_over_ratedcapacity_2019 +  theme(legend.position = c(0.25,0.9))

#save plot as image
ggsave("results_of_analysis/electricity_rated_capacity.png",
       plot = last_plot(),
       dpi = 900,
       width = 7,
       height = 4)

#linear models with rated capacity over commissioning date
lm_rated_capacity_over_time_2019 <- lm(
  amprion_2019$leistung ~ amprion_2019$inbetriebnahme)
summary(lm_rated_capacity_over_time_2019)
plot(lm_rated_capacity_over_time_2019)

#Plot rated capacity over commissioning date with linear trend 2017 - 2019
prated_capacity_over_commission <- ggplot() +
  geom_point(data = amprion_2019, 
             aes(x=inbetriebnahme, y=leistung), 
             size = 0.4, colour = "#94fc03") +
  geom_smooth(data = amprion_2019, 
              aes(x=inbetriebnahme, y=leistung, colour = "2019"), 
              method=lm, se=TRUE, fullrange = TRUE, size = 0.5)  +
  theme_light() +
  scale_x_date(limits = as.Date(c("1990-01-01","2030-12-31"))) +
  ylim(-1000, 6000) +
  xlab("Commissioning Date") +
  ylab("Rated capacity [kW]") +
  theme( axis.text=element_text(size=11),
         axis.title=element_text(size=12),
         plot.title = element_text(size=14),
         legend.position = c(0.85, 0.9),
         legend.direction = "horizontal") +
  geom_hline(yintercept = 3500, linetype = 'dashed', size = 0.25) +
  annotate(geom="text",x=as.Date("1997-01-01"),
           y=3300,label="mean of ~ 3,500 kW in 2021", size = 2.5) +
  geom_hline(yintercept = 4500, linetype = 'dashed', size = 0.25) +
  annotate(geom="text",x=as.Date("1997-01-01"),
           y=4700,label="Predicted mean of ~ 4,500 kW in 2030", size = 2.5) +
  annotate(geom="text",x=as.Date("2025-01-01"),
           y=0,label= "R² = ~ 70 %") +
  scale_colour_manual(name = "Year", values="#94fc03") 

#print plot
prated_capacity_over_commission +  theme(legend.position = c(0.25,0.9))

#save plot as image
ggsave("results_of_analysis/rated_capacity_over_commissioning.png",
       plot = last_plot(),
       dpi = 900,
       width = 7,
       height = 4)

#linear models with full load hours  over the commissioning date 2015 - 2019
#2015
lm_flh_2015 <- lm(
  amprion_2015$flh ~ amprion_2015$inbetriebnahme)
summary(lm_flh_2015)
plot(lm_flh_2015)

#2016
lm_flh_2016 <- lm(
  amprion_2016$flh ~ amprion_2016$inbetriebnahme)
summary(lm_flh_2016)
plot(lm_flh_2016)

#2017
lm_flh_2017 <- lm(
  amprion_2017$flh ~ amprion_2017$inbetriebnahme)
summary(lm_flh_2017)
plot(lm_flh_2017)

#2018
lm_flh_2018 <- lm(
  amprion_2018$flh ~ amprion_2018$inbetriebnahme)
summary(lm_flh_2018)
plot(lm_flh_2018)

#2019
lm_flh_2019 <- lm(
  amprion_2019$flh ~ amprion_2019$inbetriebnahme)
summary(lm_flh_2019)
plot(lm_flh_2019)

#plot full load hours over commissioning date with trend
pflh <- ggplot() +
  geom_point(data = amprion_2015, aes(x=inbetriebnahme, y=flh), 
             size = 0.4, colour = "#fd00e2") +
  geom_point(data = amprion_2016, aes(x=inbetriebnahme, y=flh), 
             size = 0.4, colour = "#fde600") +
  geom_point(data = amprion_2017, aes(x=inbetriebnahme, y=flh), 
             size = 0.4, colour = "#03a1fc") +
  geom_point(data = amprion_2018, aes(x=inbetriebnahme, y=flh), 
             size = 0.4, colour = "#fc5a03") +
  geom_point(data = amprion_2019, aes(x=inbetriebnahme, y=flh), 
             size = 0.4, colour = "#94fc03") +
  geom_smooth(data = amprion_2015, 
              aes(x=inbetriebnahme, y=flh, colour = "2015"), 
              method=lm, se=TRUE, fullrange = TRUE, size = 0.5)  +
  geom_smooth(data = amprion_2016, 
              aes(x=inbetriebnahme, y=flh, colour = "2016"), 
              method=lm, se=TRUE, fullrange = TRUE, size = 0.5)  +
  geom_smooth(data = amprion_2017, 
              aes(x=inbetriebnahme, y=flh, colour = "2017"), 
              method=lm, se=TRUE, fullrange = TRUE, size = 0.5)  +
  geom_smooth(data = amprion_2018, 
              aes(x=inbetriebnahme, y=flh, colour = "2018"),
              method=lm, se=TRUE, fullrange = TRUE, size = 0.5)  +
  geom_smooth(data = amprion_2019, 
              aes(x=inbetriebnahme, y=flh, colour = "2019"), 
              method=lm, se=TRUE, fullrange = TRUE, size = 0.5)  +
  theme_light() +
  scale_x_date(limits = as.Date(c("1990-01-01","2030-12-31"))) +
  ylim(0, 4000) +
  xlab("Commissioning Date") +
  ylab("Full load hours [h/a]") +
  theme( axis.text=element_text(size=11),
         axis.title=element_text(size=12),
         plot.title = element_text(size=14),
         legend.position = c(0.85, 0.9),
         legend.direction = "horizontal") +
  geom_hline(yintercept = 2300, linetype = 'dashed', size = 0.25) +
  annotate(geom="text",x=as.Date("1997-01-01"),
           y=2200,label="mean of ~ 2,300 h/a in 2021 with linear trends", 
           size = 2.5) +
  geom_hline(yintercept = 2800, linetype = 'dashed', size = 0.25) +
  annotate(geom="text",x=as.Date("2000-01-01"),
           y=2900,label="mean of ~ 2,800 h/a in 2030 with linear trends", 
           size = 2.5) +
  geom_hline(yintercept = 15000, linetype = 'dashed', size = 0.25) +
  annotate(geom="text",x=as.Date("2003-01-01"),
           y=14200, label="> 15,000 MWh/a in 2030 with polynomial models", 
           size = 2.5) +
  annotate(geom="text",x=as.Date("2026-01-01"),
           y=800,label= "All R²  ~ 46 - 51 %", size = 2.5) +
  annotate(geom="text",x=as.Date("2026-01-01"),
           y=400,label="p-values all << 0.001", size = 2.5) +
  scale_colour_manual(name = "Year", 
                      values=c("#fd00e2", "#fde600", 
                               "#03a1fc", "#fc5a03", "#94fc03")) 

#print plot
pflh +  theme(legend.position = c(0.35,0.93))

#save plot as image
ggsave("results_of_analysis/flh.png",
       plot = last_plot(),
       dpi = 900,
       width = 7,
       height = 4)
```
\newpage
## Code chunk 2
```{r, eval=FALSE, echo=TRUE}
################################
#geospatial distance estimation#
################################

Sys.setenv(LANG = "en")
pacman::p_load(data.table, tidyverse, magrittr, leaflet, sp, raster, htmltools,
               htmlwidgets, sf, spatstat, rgeos, rgdal, DiagrammeR)

#import data
MaStR_amprion <- read.csv("MaStR_amprion2019.csv")
attach(MaStR_amprion)

#change lat and long to numeric
MaStR_amprion$l_wgs84 <- gsub(",",".", l_wgs84)  
MaStR_amprion$b_wgs84 <- gsub(",",".", b_wgs84)
MaStR_amprion$b_wgs84 <- as.numeric(MaStR_amprion$b_wgs84)
MaStR_amprion$l_wgs84 <- as.numeric(MaStR_amprion$l_wgs84)

#load boundaries of RLP
border_sf  <- st_read("Borders_RLP_shape/Landesgrenze_RLP.shp")
border_sp <- readOGR("Borders_RLP_shape/Landesgrenze_RLP.shp")

#create coordinate columns and check CRS
class(MaStR_amprion)
coordinates(MaStR_amprion) <- ~ l_wgs84 + b_wgs84
crs(MaStR_amprion)

#create crs
WGS84 <- CRS("+proj=longlat +datum=WGS84 +no_defs")
crs(MaStR_amprion) <- WGS84
crs(MaStR_amprion)

#clip those inside RLP 
wts_rlp <- MaStR_amprion[border_sp,]
wts_rlp_df <- as.data.frame(wts_rlp)


#convert point layer to in sf format
wts_rlp_sf <- st_as_sf(wts_rlp)
crs(wts_sf)
class(wts_sf)

#transform point layer of wts to flat
wts_rlp_flat <- st_transform(wts_rlp_sf, crs = 6345)
plot(wts_rlp_flat)

#transform border polygon of RLP to flat
border_flat <- st_transform(border_sf, crs = 6345)

##############################
#PPA - Point Pattern Analysis#
##############################

#create ppp formate of WT's
wts_rlp_ppp  <- as.ppp(wts_rlp_flat)
plot(wts_rlp_ppp)

#create owin format
border_owin <- as.owin(border_flat)

#create window of points with borders of rlp and plot
Window(wts_rlp_ppp) <- border_owin
plot(wts_rlp_ppp, cols=rgb(0,0,0,.2), pch=20)

#calculate average nearest neighbor 
mean(nndist(wts_rlp_ppp, k=1))
#~549m -----> seems reasonable

#calculate nearest neighbor
nearest <- nndist(wts_rlp_ppp, k=1)

wts_rlp_distances <- data.frame(wts_rlp_df, nearest)
wts_rlp_distances$nearest <- round(wts_rlp_distances$nearest)


#plot with leaflet
leaflet(data = wts_rlp_distances) %>% 
  addTiles() %>% 
  addPolygons(data = border_sp,
              color = "#5DADE2",
              weight = 2,
              opacity = 0.6,
              fillColor = "#5DADE200",
              highlight = highlightOptions(weight = 7,
                                           color = "#5DADE2",
                                           fillColor = "#5DADE2",
                                           fillOpacity = 0.3,
                                           bringToFront = TRUE),
              label = "Rheinland-Pfalz",
              group = "Rheinland-Pfalz") %>%
  addMarkers(lng = wts_rlp$l_wgs84,
             lat = wts_rlp$b_wgs84,
             clusterOptions = markerClusterOptions(disableClusteringAtZoom = 10),
             popup = ~paste("<h3> Daten der Windkraftanlage</h3>",
                            "<b>Distance to next WT:</b>", nearest, "<br>"))

#create colum with mwh and area
wts_rlp_distances <- wts_rlp_distances %>%
  mutate(menge_mwh = round(menge_kwh/1000)) %>% 
  mutate(area_m2 = round(nearest^2)) %>% 
  mutate(area_km2 = round(area_m2/1000000, digits = 3)) %>% 
  mutate(kwh_m2 = round(menge_kwh/area_m2, digits = 3)) %>% 
  mutate(d = round(nearest/rotor_m))

#write csv file 
write.csv(wts_rlp_distances, "wts_rlp_distances.csv")
```



## Code chunk 3
```{r rotorhubcode, eval=FALSE, echo=TRUE}
########################################################################
#Analysis of rotor diameter, hub heights and electricity yield per area#
########################################################################

Sys.setenv(LANG = "en")
pacman::p_load(data.table, tidyverse, magrittr, leaflet, htmltools,
               htmlwidgets, gridExtra)

#import data
wts_rlp_distances <- read.csv(
  "result_of_distance_estimation/wts_rlp_distances.csv")

#change date format
wts_rlp_distances$inbetriebnahme <- as.Date(
  wts_rlp_distances$inbetriebnahme, "%Y-%m-%d")

############################
#Analysis of rotor diameter#
############################
wts_rlp_rotor <- filter(wts_rlp_distances, rotor_m != "NA")
wts_rlp_rotor <- filter(wts_rlp_rotor, rotor_m < 200)
sum(is.na(wts_rlp_rotor$rotor_m))
mean(wts_rlp_rotor$rotor_m)
#86.54686 m

#linear model of rotor diameter over commissioning
lm_rotor <- lm(wts_rlp_rotor$rotor_m ~ wts_rlp_rotor$inbetriebnahme)
summary(lm_rotor)
plot(lm_rotor)

#plot rotor diameter over commissioning date
p_rotor <- ggplot() +
  geom_point(data = wts_rlp_rotor, aes(x=inbetriebnahme, y=rotor_m), 
             size = 0.4, colour = "#fde600") +
  geom_smooth(data = wts_rlp_rotor, 
              aes(x=inbetriebnahme, y=rotor_m, colour = "2019"), 
              method=lm, se=TRUE, fullrange = TRUE, size = 0.5)  +
  theme_light() +
  ylim(25,170) +
  scale_x_date(limits = as.Date(c("1990-01-01","2030-12-31"))) +
  xlab("Commissioning date") +
  ylab("Rotor diameter [m]") +
  theme( axis.text=element_text(size=11),
         axis.title=element_text(size=12),
         plot.title = element_text(size=14),
         legend.position = c(0.85, 0.9),
         legend.direction = "horizontal") +
  annotate(geom="text",x=as.Date("2025-01-01"),
           y=50,label= "R² = 68.7 % \n p-value << 0.001") +
  scale_colour_manual(name = "Data from MaStR", 
                      values="#fde600") +
  theme(legend.position = c(0.3,0.9))


########################
#Analysis of hub height#
########################
wts_rlp_nabe <- filter(wts_rlp_distances, nabe_m != "NA")
wts_rlp_nabe <- filter(wts_rlp_nabe, nabe_m < 200)
sum(is.na(wts_rlp_nabe$nabe_m))
mean(wts_rlp_nabe$nabe_m)
#110.3489 m

#linear model
lm_nabe <- lm(wts_rlp_nabe$nabe_m ~ wts_rlp_nabe$inbetriebnahme)
summary(lm_nabe)
plot(lm_nabe)

#plot hub height over commissioning date
p_nabe <- ggplot() +
  geom_point(data = wts_rlp_nabe, aes(x=inbetriebnahme, y=nabe_m), 
             size = 0.4, colour = "#fc5a03") +
  geom_smooth(data = wts_rlp_nabe, 
              aes(x=inbetriebnahme, y=nabe_m, colour = "2019"), 
              method=lm, se=TRUE, fullrange = TRUE, size = 0.5)  +
  theme_light() +
  ylim(25,220) +
  scale_x_date(limits = as.Date(c("1990-01-01","2030-12-31"))) +
  xlab("Commissioning date") +
  ylab("Hub height [m]") +
  theme( axis.text=element_text(size=11),
         axis.title=element_text(size=12),
         plot.title = element_text(size=14),
         legend.position = c(0.85, 0.9),
         legend.direction = "horizontal") +
  annotate(geom="text",x=as.Date("2025-01-01"),
           y=50,label= "R² = 77.9 % \n p-value << 0.001") +
  scale_colour_manual(name = "Data from MaStR", 
                      values="#fc5a03") +
  theme(legend.position = c(0.3,0.9))

p_nabe

#plot both in one
grid.arrange(p_rotor, p_nabe, ncol=1)

#save plot
ggsave("results_of_analysis/rotor_diameter_hub_height.png",
       plot = grid.arrange(p_rotor, p_nabe, ncol=1),
       dpi = 900,
       width = 7,
       height = 4)

par(mfrow=c(1,1))
########################################
#Analysis of electricity yield per area#
########################################

#remove WT's that have distance greater than 1000 m equal to zero 
wts_rlp_filtered <- filter(wts_rlp_distances, nearest < 1000 & nearest != 0)

#omit NA values 
sum(is.na(wts_rlp_filtered$menge_mwh))
wts_rlp_filtered <- na.omit(wts_rlp_filtered)

#filter those with electricity yield smaller than 10 Mwh and small distance 
wts_rlp_filtered <- filter(wts_rlp_filtered, menge_mwh > 20)
wts_rlp_filtered <- filter(wts_rlp_filtered, nearest > 30)

#filter out with electricity yield per m2 above 100 kwh/m2 
wts_rlp_filtered <- filter(wts_rlp_filtered, kwh_m2 < 500)

#create linear model
lm_e_yield_per_area <- lm(
  wts_rlp_filtered$kwh_m2 ~ wts_rlp_filtered$inbetriebnahme)
summary(lm_e_yield_per_area)
plot(lm_e_yield_per_area)

#calculate average distance in relation to rotor diameter
mean(wts_rlp_filtered$d)
#4.983264

#calculate mean distance again and area consumption with average
mean(wts_rlp_filtered$nearest)
#~417.3347m that means 169,744 m2 or 0.17 km2 per WT
#area of RLP 19847
#total are consumption with 1702 WT's is  289.34 km2 this is about 289,340,000 m2
#that is 1.457 % of RLP
#with a total electricity yield of 6,782 TWh that means 23,439 kWh/m2
#constant power output of 2.675 W/m2
#calculate wind speed with third root of electricity yield per area divided 
#by 0.016 * 1.3 * 0.5 = 0.0104
#2.675/0.0104 = 257.2115
#250.9827^(1/3)
#wind speed with 6.359605 m/s required


#calculate actual total mean electricity yield per m2 in data
mean(wts_rlp_filtered$kwh_m2)
#~26.17383 kwh/m2 
#Calculate average power per area with 23.3(1000/8765)
#~2.6583 W/m2
#2.6583/0.0104 = 255.6058
#255.6058^(1/3) = 6.346343 m/s wind speed required
#calculate area consumption of 22 TWh with ~23.3 kWh/m2
#22*(1e+09kwh/23.3 kwh/m2) = 943422522m2 = 943.4225km2 = 4.753477 % 
# = 3.168985 times the current area

#calculate area consumption with mean of WT's built after 2010
wts_rlp_filtered_2010 <- filter(wts_rlp_filtered, inbetriebnahme > "2010-01-01")
mean(wts_rlp_filtered_2010$nearest)
#467.9847 m
mean(wts_rlp_filtered_2010$d)
#4.60781 times d
mean(wts_rlp_filtered_2010$area_m2)
#238527.4 m2
mean(wts_rlp_filtered_2010$area_km2)
#0.2385161 km2
mean(wts_rlp_filtered_2010$kwh_m2)
#30.46168 kWh/m2
#3.477361 W/m2


#plot electricity yield per area over commissioning date
p_e_yield_per_area <- ggplot() +
  geom_point(data = wts_rlp_filtered, aes(x=inbetriebnahme, y=kwh_m2), 
             size = 0.4, colour = "#00A2ff") +
  geom_smooth(data = wts_rlp_filtered, 
              aes(x=inbetriebnahme, y=kwh_m2, colour = "2019"), 
              method=lm, se=TRUE, fullrange = TRUE, size = 0.5)  +
  theme_light() +
  ylim(0,80) +
  scale_x_date(limits = as.Date(c("1990-01-01","2030-12-31"))) +
  xlab("Commissioning date") +
  ylab("Electricity yield per area [kWh/m²a]") +
  theme( axis.text=element_text(size=11),
         axis.title=element_text(size=12),
         plot.title = element_text(size=14),
         legend.position = c(0.85, 0.9),
         legend.direction = "horizontal") +
  geom_hline(yintercept = 33.5, linetype = 'dashed', size = 0.25) +
  annotate(geom="text",x=as.Date("1995-01-01"),
           y=35.5,label="Predicted mean of  ~ 33.5 kWh/m²a in 2021", 
           size = 2.5) +
  geom_hline(yintercept = 40.5, linetype = 'dashed', size = 0.25) +
  annotate(geom="text",x=as.Date("1995-01-01"),
           y=42.5,label="Predicted mean of ~ 40.5 kWh/m²a in 2030",
           size = 2.5) +
  annotate(geom="text",x=as.Date("2025-01-01"),
           y=5,label= "R² = ~ 11 % \n p-value << 0.001") +
  scale_colour_manual(name = "Joined data from MaStR and amprion", 
                      values="#00A2ff")

#plot
p_e_yield_per_area +  theme(legend.position = c(0.7,0.9))

#save plot
ggsave("results_of_analysis/e_yield_per_m2_over_commissioning_date.png",
       plot = last_plot(),
       dpi = 900,
       width = 7,
       height = 4)


#the model assumes an average of around 33.5 kWh/m2a in 2021
#3.822019 W/m2
#3.822019/0.0104 = 367.5018 (5d)
#3.822019/0.0436 = 87.66099 (3d)
#367.5018^(1/3) = 7.16286 m/s wind speed required (5d)
#87.66099^(1/3) = 4.442241 m/s wind speed required (3d)
#wind speed of 7.16286 m/s
##calculate area consumption of 22 TWh
#This requires an area of 656716418 m2 = 656.7164 km2 = 3.308895 % 
#= 2.20593 times as much WT's

#if average is 40.5 kwh/m2a in 2030
#4.62065 W/m2
#4.62065/0.0104 = 444.2933 (5d)
#4.62065/0.0436 = 105.9782 (3d)
#444.2933^(1/3) = 7.630563 m/s wind speed required (5d)
#105.9782^(1/3) = 4.732299 m/s wind speed required (3d)
#area consumption with demand of 22 TWh
# 543209877 m2 = 543.2099 km2 = 2.736987 % = 1.824658 times as much

#if average is 63.5 kWh/m2a in 2030
#7.2 W/m2
#7.2/0.0104 = 692.3077 (5d)
#7.2/0.0436 = 165.1376
#692.3077^(1/3) = 8.846396 m/s (5d)
#165.1376^(1/3) = 5.486331 m/s (3d)
#area of 346.456 km2 = 1.74 %
```





